name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}
          load: true

      - name: Create Docker container
        run: |
          docker run -d --name ml ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}

      - name: Run Tests in Docker container
        run: |
          docker exec ml python -m unittest discover tests

      - name: Stop Docker container
        run: |
          docker stop ml
          docker rm ml

      - name: Push to Amazon ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.ECR_REPOSITORY_URL }}:${{ github.sha }}
